language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -q -e .
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=massadmin manage.py test --settings=tests.settings
after_success:
  coveralls
matrix:
  allow_failures:
     - env: DJANGO="Django>=3.0,<3.1"
